import { TYPE_FIELD } from "constant/enums";
import { InputFiledParams } from "constants/types/Form_Field_type";
import { ColumnProps } from "constants/types/common.type";
const { INPUT, SELECT, INPUT_NUMBER, GET_LOCATION_BTN } = TYPE_FIELD;
const css = { xs: 24, sm: 24, md: 24, lg: 12, xl: 12 };
const wrapperCol = { xs: 20, sm: 20, md: 20, lg: 16, xl: 16 };
const labelCol = { xs: 4, sm: 4, md: 4, lg: 8, xl: 8 };
const fields1: InputFiledParams[] = [
  {
    key: 1,
    label: "Số thửa",
    name: "landPlotNumber",
    type: INPUT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 2,
    label: "Số tờ bản đồ",
    name: "mapSheetNumber",
    type: INPUT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
];
const columns: ColumnProps[] = [
  {
    title: "Địa chỉ",
    dataIndex: "stt",
    key: "stt",
    render: (text: any) => {
      return <>Hồ sơ pháp lý</>;
    },
    width: 100,
    show: true,
    align: "center",
  },

  {
    type: SELECT,
    dataIndex: "addressProvince",
    key: "addressProvince",
    title: "Tỉnh/Thành phố (*)",
    show: true,
    rules: [{ required: true, message: "Chưa chọn Tỉnh/Thành phố" }],
  },
  {
    type: SELECT,
    dataIndex: "addressDistrict",
    key: "addressDistrict",
    title: "Quận/Huyện/TP/Thị xã (*)",
    show: true,
    rules: [{ required: true, message: "Chưa chọn Quận/Huyện/TP/Thị xã" }],
  },
  {
    type: SELECT,
    dataIndex: "addressWard",
    key: "addressWard",
    title: "Xã/Phường/Thị trấn (*)",
    show: true,

    rules: [{ required: true, message: "Chưa chọn Xã/Phường/Thị trấn" }],
  },
  {
    type: INPUT,
    dataIndex: "addressStreet",
    key: "addressStreet",
    title: "Đường phố",
    show: true,
  },
  {
    type: INPUT,
    dataIndex: "addressDetail",
    key: "addressDetail",
    title: "Chi tiết",
    show: true,
  },
  {
    type: GET_LOCATION_BTN,
    dataIndex: "action_locate",
    key: "action_locate",
    show: true,
    align: "center",
  },
];
const fields2: any[] = [
  {
    key: 3,
    label: "Tọa độ (X)",
    name: "latitude",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 3,
    label: "Tọa độ (Y)",
    name: "longitude",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 2,
    label: "Diện tích phù hợp quy hoạch (m²)",
    name: "areaInplan",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
    show: true,
    rules: [{ required: true, message: "Vui lòng nhập diện tích PHQH" }],
  },
  {
    key: 3,
    label: "Diện tích không phù hợp quy hoạch (m²)",
    name: "areaUnplan",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
    show: true,
    rules: [{ required: true, message: "Vui lòng nhập diện tích KPHQH" }],
  },
  {
    key: 1,
    label: "Diện tích khuôn viên (m²)",
    name: "areaWidth",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
    show: true,
    rules: [{ required: true, message: "Vui lòng nhập diện tích khuôn viên" }],
  },
  {
    key: 4,
    label: "Mục đích sử dụng đất",
    name: "usingPurposeId",
    type: SELECT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    show: true,
    rules: [{ required: true, message: "Vui lòng chọn mục đích sử dụng đất" }],
  },
  {
    key: 5,
    label: "Hình dạng",
    name: "shape",
    type: INPUT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 6,
    label: "Số mặt tiền/mặt thoáng",
    name: "numberOfFacade",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
  },

  {
    key: 3,
    label: "Phạm vi bán kính (km)",
    name: "radius",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
  },
  {
    key: 7,
    label: "Kích thước mặt tiền (m)",
    name: "facadeLength",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
  },
  {
    key: 8,
    label: "Đoạn đường trong khung giá",
    name: "roadInPriceRange",
    type: SELECT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 9,
    label: "Loại đường tiếp giáp",
    name: "roadContiguousTypeId",
    type: SELECT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 10,
    label: "Vị trí",
    name: "positionId",
    type: SELECT,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
  },
  {
    key: 11,
    label: "Độ rộng đường (m)",
    name: "widthToMainRoad",
    type: INPUT_NUMBER,
    css: css,
    wrapperCol: wrapperCol,
    labelCol: labelCol,
    currencable: true,
  },
];

export { fields1, fields2, columns };
