import { ColumnsEdit } from "components/TableInputAddCustom/TableInputAddCustom";
import { AppraisalFileAssetCommonType } from "constant/types";

const columnsTableMenu: ColumnsEdit = [
  {
    key: "index",
    dataIndex: "index",
    title: "STT",
    align: "center",
  },
  {
    key: 1,
    dataIndex: "assetCodeView",
    title: "Mã tài sản",
    align: "center",
    className: "width-size-max",
    editable: true,
    disable: true,
  },
  {
    key: 2,
    dataIndex: "climsCode",
    title: "Mã CLIMS",
    align: "center",
    className: "width-size-max",
    editable: true,
    disable: true,
  },
  {
    key: 6,
    dataIndex: "appraisalTypeId",
    title: "Định giá qua SBA",
    align: "center",
    className: "width-size-max",
    selected: true,
    disable: true,
  },
  {
    key: 3,
    title: "Phân loại tài sản",
    selected: true,
    showSearch: true,
    align: "center",
    dataIndex: "assetLevelThreeId",
    className: "width-size-max-asset",
  },
  {
    key: 7,
    title: "Tình trạng pháp lý",
    dataIndex: "legalStatusId",
    align: "center",
    className: "width-size-max",
    selected: true,
    disable: true,
  },
  // {
  //   key: 8,
  //   title: "Số GCN/HĐ",
  //   dataIndex: "legalNumber",
  //   align: "left",
  //   className: "width-size-max",
  //   width: "100px",
  //   editable: true,
  //   disable: true,
  // },
  {
    key: 9,
    title: "Tỉnh/Thành phố",
    dataIndex: "addressProvince",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 10,
    title: "Quận/Huyện/Thị xã",
    dataIndex: "addressDistrict",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 11,
    title: "Xã/Phường/Thị trấn",
    dataIndex: "addressWard",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 12,
    title: "Mô tả chi tiết",
    dataIndex: "description",
    align: "center",
    className: "width-size-max",
    editable: true,
    popupInput: true,
    maxLength: 255,
    placeholder: "Nhập",
  },
  {
    key: 13,
    title: "Đường",
    dataIndex: "addressStreet",
    align: "center",
    className: "width-size-max",
    editable: true,
    popupInput: true,
    maxLength: 255,
    placeholder: "Nhập",
  },
  // {
  //   key: "action",
  //   dataIndex: "",
  //   align: "center",
  //   width: "4%",
  //   fixed: "right",
  // },
];

const newItem: AppraisalFileAssetCommonType = {
  addressDistrict: null,
  addressProvince: null,
  addressWard: null,
  appraisalTypeId: null,
  assetLevelThreeId: null,
  legalNumber: "",
  legalStatusId: null,
  addressDetail: "",
  addressStreet: "",
  appraisalType: null,
  assetLevelThree: null,
  districts: null,
  legalStatus: null,
  provinces: null,
  wards: null,
  appraisalFileId: null,
  assetCode: "",
  assetCommonId: null,
  climsCode: null,
  assetLevelThreeName: null,
  description: null,
  key: "",
};

export { columnsTableMenu, newItem };
