import { AppraisalFileCreateType } from "constant/types/appraisalFile";

const initialAppraisalFile: AppraisalFileCreateType = {
  customer: null,
  branchCode: null,
  branch: null,
  transOfficeCode: null,
  transOffice: null,
  rmName: null,
  rmPhone: null,
  resultEmail: null,
  invoiceEmail: null,
  surveyGuide: null,
  surveyGuidePhone: null,
  surveyTime: null,
  proposalDate: null,
  approvedDate: null,
  fileStatus: null,
  assetName: null,
  appraisalPurposeId: null,
  appraisalPurpose: null,
  assetLevelOneId: null,
  assetLevelOne: null,
  assetLevelTwoId: null,
  assetLevelTwo: null,
  assetLevelThrees: null,
  address: null,
  addressDetail: null,
  addressStreet: null,
  addressWard: null,
  addressDistrict: null,
  addressProvince: null,
  latitude: null,
  longitude: null,
  flowId: 1,
  surveyer: null,
  appraiser: null,
  appraisalUnit: null,
  assetCommons: [],
  assetImages: [],
  surveySchedules: [],
  legalDocuments: [],
  flow: null,
};

export { initialAppraisalFile };
