import { TYPE_FIELD } from "constant/enums";
const { SELECT } = TYPE_FIELD;
export const dataSource = [
  {
    key: "1",
    name: "Thông tin tham chiếu",
    align: "center",
    lable: "Mã tài sản kho giá",
    ts1: "tstd",
    ts2: "ts1",
    ts3: "ts2",
    ts4: "ts3",
    required: false,
    typeFiled: SELECT,
  },
  {
    key: "2",
    name: "Thông tin tham chiếu",
    lable: "Nguồn dữ liệu",
    ts1: "-",
    ts2: "ts2",
    ts3: "ts3",
    ts4: "ts4",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "3",
    name: "Thông tin tham chiếu",
    lable: "Nguồn thông tin",
    ts1: "-",
    ts2: "ts2",
    ts3: "ts3",
    ts4: "ts4",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "4",
    name: "Thông tin tham chiếu",
    lable: "Người liên hệ - SĐT",
    ts1: "-",
    ts2: "ts2",
    ts3: "ts3",
    ts4: "ts4",
    required: true,
  },
  {
    key: "5",
    name: "Thông tin tham chiếu",
    lable: "Tình trạng giao dịch",
    ts1: "-",
    ts2: "ts2",
    ts3: "ts3",
    ts4: "ts4",
    required: true,
  },
  {
    key: "6",
    name: "Thông tin tham chiếu",
    lable: "Thời điểm",
    ts1: "-",
    required: true,
  },
  {
    key: "7",
    name: "Địa chỉ",
    lable: "Tỉnh/TP",
    ts1: "Thành phố Hồ Chí Minh",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "8",
    name: "Địa chỉ",
    lable: "Quận/Huyện/TP/Thị xã",
    ts1: "Quận 1",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "9",
    name: "Địa chỉ",
    lable: "Xã/Phường/Thị trấn",
    ts1: "Phường Đa Kao",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "10",
    name: "Địa chỉ",
    lable: "Đường phố",
    ts1: "Nguyễn Thị Minh Khai",
    required: true,
  },
  {
    key: "11",
    name: "Địa chỉ",
    lable: "Vị trí",
    ts1: "Mặt tiền",
    required: true,
    typeFiled: SELECT,
  },
  {
    key: "12",
    name: "Địa chỉ",
    lable: "Số tờ",
    ts1: "15",
    required: true,
  },
  {
    key: "13",
    name: "Địa chỉ",
    lable: "Số thửa",
    ts1: "324",
    required: true,
  },
  {
    key: "14",
    name: "Địa chỉ",
    lable: "Chi tiết",
    ts1: "Nhà hẻm Nguyễn Thị Minh Khai",
  },
  {
    key: "15",
    name: "Địa chỉ",
    lable: "Định vị",
    ts1: 24,
    typeFiled: "LOCAL",
  },
  {
    key: "16",
    name: "Chi tiết",
    lable: "Hình ảnh tài sản",
    typeFiled: "IMAGE",
    ts1: 68,
  },
  {
    key: "17",
    name: "Chi tiết",
    lable: "Tên dự án/Khu công nghiệp",
    ts1: "-",
  },
  {
    key: "18",
    name: "Chi tiết",
    lable: "Diện tích khuôn viên (m²)",
    ts1: "643",
    required: true,
  },
  {
    key: "19",
    name: "Chi tiết",
    lable: "Diện tích phù hợp quy hoạch (m²)",
    ts1: "643",
    required: true,
  },
  {
    key: "111",
    name: "Chi tiết",
    lable: "Diện tích không phù hợp quy hoạch (m²)*",
    ts1: "643",
    required: true,
  },
  {
    key: "20",
    name: "Chi tiết",
    lable: "Kích thước mặt tiền (m)",
    ts1: "220",
    required: true,
  },
  {
    key: "21",
    name: "Chi tiết",
    lable: "Số mặt tiền tiếp giáp",
    ts1: "1",
  },
  {
    key: "22",
    name: "Chi tiết",
    lable: "Hình dạng",
    ts1: "Chữ nhật",
  },
  {
    key: "23",
    name: "Chi tiết",
    lable: "Độ rộng đường/hẻm chính/hẻm phụ",
    ts1: "16",
  },
  {
    key: "24",
    name: "Chi tiết",
    lable: "Khoảng cách tới trục đường chính (m)",
    ts1: "16",
  },
  {
    key: "25",
    name: "Chi tiết",
    lable: "Lợi thế kinh doanh",
    ts1: "Tốt",
  },
  {
    key: "26",
    name: "Chi tiết",
    lable: "Mục đích sử dụng đất",
    ts1: "Kinh doanh",
  },
  {
    key: "2722",
    name: "Chi tiết",
    lable: "Yếu tố khác",
    ts1: "Không",
  },
  {
    key: "27",
    name: "Chi tiết",
    lable: "Giá giao dịch/ rao bán (đồng)",
    ts1: "-",
    required: true,
  },
  {
    key: "28",
    name: "Chi tiết",
    lable: "Giá ước tính (đồng)*",
    ts1: "-",
    required: true,
  },
  {
    key: "29",
    name: "Chi tiết",
    lable: "Tổng diện tích sàn XD (m²)",
    ts1: "643",
  },
  {
    key: "30",
    name: "Chi tiết",
    lable: "Đơn giá XD (đồng/m²)",
    ts1: "-",
  },
  {
    key: "31",
    name: "Chi tiết",
    lable: "CLCL (%)",
    ts1: "80%",
  },
  {
    key: "32",
    name: "Chi tiết",
    lable: "Giá trị CTXD (đồng)",
    ts1: "-",
  },
  {
    key: "33",
    name: "Chi tiết",
    lable: "Đơn giá đất (đồng/m²)",
    ts1: "-",
  },
];
