import type { ColumnsType } from "antd/es/table";
import { numberUtils } from "utils";

const defaultColumns: ColumnsType<any> = [
  {
    key: 0,
    title: "STT",
    dataIndex: "index",
    align: "center",
    render: (text, record, rowIndex) => rowIndex + 1,
    fixed: "left",
    width: "50px",
  },
  {
    key: 1,
    title: "Tên KH",
    dataIndex: "customerName",
    align: "left",
    fixed: "left",
    width: "200px",
  },
  {
    key: 2,
    title: "Địa chỉ thẩm định",
    dataIndex: "addressAppraisal",
    align: "left",
    fixed: "left",
    width: "200px",
  },
  {
    key: 3,
    title: "Số hồ sơ Clim",
    dataIndex: "climsCode",
    align: "left",
    fixed: "left",
    width: "200px",
  },
  {
    key: 4,
    title: "Số hồ sơ",
    dataIndex: "fileCode",
    align: "left",
    fixed: "left",
    width: "200px",
  },
  {
    key: 5,
    title: "Ngày nhận",
    dataIndex: "receiveDate",
    align: "left",
    width: "200px",
  },
  {
    key: 6,
    title: "CN/PGD",
    dataIndex: "branchName",
    align: "left",
    width: "200px",
  },
  {
    key: 7,
    title: "ĐGV",
    dataIndex: "dgv",
    align: "left",
    width: "200px",
  },
  {
    key: 8,
    title: "CBTĐ/Email",
    dataIndex: "email",
    align: "left",
    width: "250px",
  },
  {
    key: 9,
    title: "ĐTDĐ",
    dataIndex: "numberPhone",
    align: "left",
    width: "135px",
  },
  {
    key: 10,
    title: "MST",
    dataIndex: "taxCode",
    align: "left",
    width: "135px",
  },
  {
    key: 11,
    title: "Địa chỉ KH",
    dataIndex: "customerAddress",
    align: "left",
    width: "200px",
  },
  {
    key: 12,
    title: "Tỉnh/TP",
    dataIndex: "province",
    align: "left",
    width: "135px",
  },
  {
    key: 13,
    title: "Tình trạng hồ sơ",
    dataIndex: "status",
    align: "left",
    width: "137px",
  },
  {
    key: 14,
    title: "Ngày huỷ",
    dataIndex: "cancelDate",
    align: "left",
    width: "200px",
  },
  {
    key: 15,
    title: "Tái cấp/Vay mới",
    dataIndex: "refinanceNewLoan",
    align: "left",
    width: "135px",
  },
  {
    key: 16,
    title: "Tổng phí",
    dataIndex: "feeTotal",
    align: "right",
    width: "200px",
    render: (text) => numberUtils.formatNumber(text),
  },
  {
    key: 17,
    title: "Công tác phí",
    dataIndex: "businessFee",
    align: "right",
    width: "200px",
    render: (text) => numberUtils.formatNumber(text),
  },
  {
    key: 18,
    title: "Phí đợt 1",
    dataIndex: "feeOne",
    align: "right",
    width: "200px",
    render: (text) => numberUtils.formatNumber(text),
  },
  {
    key: 19,
    title: "Phí đợt 2",
    dataIndex: "feeTwo",
    align: "right",
    width: "200px",
    render: (text) => numberUtils.formatNumber(text),
  },
  {
    key: 20,
    title: "Tổng giá trị tài sản",
    dataIndex: "assetTotal",
    align: "right",
    width: "200px",
    render: (text) => numberUtils.formatNumber(text),
  },
];

export { defaultColumns };
