export const mockData = {
  constructions: [
    {
      constructionId: 27399,
      assetLandInforId: 12512,
      constructionTypeId: 1,
      constructionType: {
        constructionTypeId: 1,
        constructionTypeName: "Biệt thự trệt",
        description: null,
      },
      constructionNameId: 1,
      constructionName: {
        constructionNameId: 1,
        constructionName:
          "Khung, mái BTCT (có hoặc không dán ngói); trần thạch cao; tường gạch sơn nước; nền lát gạch bóng kính hay tương đương.",
        constructionTypeId: 1,
        lowPrice: 6500000,
        highPrice: 8000000,
      },
      constructionArea: 100.0,
      constructionAreaApprovaled: 100.0,
      constructionLegalTypeId: 1,
      floors: 2.0,
      baseFloors: null,
      furnitures: "Đẩy đủ",
      constructionYear: 2020,
      repairYear: null,
      remainingQuality: 90.0,
      remainingQualityApprovaled: 90.0,
      mdhtApprovaled: null,
      mdht: null,
      unitPrice: 7000000,
      unitPriceApprovaled: 7000000,
      totalValue: 630000000,
      totalValueApprovaled: 630000000,
      describe: null,
      whoCreate: "cvtd1-sba@sacombank.com",
      dateCreate: "2024-07-01T02:34:21.504+00:00",
      dateModify: "2024-07-01T02:34:21.504+00:00",
      consolidationParentID: null,
      orderBy: 0,
    },
    {
      constructionId: 27400,
      assetLandInforId: 12512,
      constructionTypeId: 1,
      constructionType: {
        constructionTypeId: 1,
        constructionTypeName: "Biệt thự trệt",
        description: null,
      },
      constructionNameId: 1,
      constructionName: {
        constructionNameId: 1,
        constructionName:
          "Khung, mái BTCT (có hoặc không dán ngói); trần thạch cao; tường gạch sơn nước; nền lát gạch bóng kính hay tương đương.",
        constructionTypeId: 1,
        lowPrice: 6500000,
        highPrice: 8000000,
      },
      constructionArea: 150.0,
      constructionAreaApprovaled: 150.0,
      constructionLegalTypeId: 1,
      floors: 2.0,
      baseFloors: null,
      furnitures: "Đầy đủ",
      constructionYear: 2021,
      repairYear: null,
      remainingQuality: 90.0,
      remainingQualityApprovaled: 90.0,
      mdhtApprovaled: null,
      mdht: null,
      unitPrice: 7250000,
      unitPriceApprovaled: 7250000,
      totalValue: 978750000,
      totalValueApprovaled: 978750000,
      describe: null,
      whoCreate: "cvtd1-sba@sacombank.com",
      dateCreate: "2024-07-01T02:34:21.504+00:00",
      dateModify: "2024-07-01T02:34:21.504+00:00",
      consolidationParentID: null,
      orderBy: 0,
    },
  ],
};
