export const APPRAISAL_FILE_STATUS = {
  LOS_RECEIVED: "LOS_RECEIVED",
  MINUS_TWO: -2,
  MINUS_ONE: -1,
  ZERO: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  SEVEN: 7,
  EIGHT: 8,
  NINE: 9,
  TEN: 10,
  ELEVEN: 11,
  TWELVE: 12,
  THIRTEEN: 13,
  FOURTEEN: 14,
  FIFTEEN: 15,
  SIXTEEN: 16,
  SEVENTEEN: 17,
  NINETEEN: 19,
  TWENTY: 20,
  TWENTY_ONE: 21,
  FORTY_ONE: 41,
  MINUS_TWO_LABEL: "Chờ báo lại lịch khảo sát",
  MINUS_ONE_LABEL: "Từ chối",
  ONE_LABEL: "Tiếp nhận từ LOS",
  ONE_PLUS_LABEL: "Hoàn thành tiếp nhận",
  ZERO_LABEL: "Tạo hồ sơ thủ công",
  TWO_LABEL: "Chờ bổ sung HSPL",
  THREE_LABEL: "Đã bổ sung HSPL",
  SIX_LABEL: "Chờ phân công",
  SEVEN_LABEL: "Chưa có lịch khảo sát",
  EIGHT_LABEL: "Đã có lịch khảo sát",
  NINE_LABEL: "Chờ bổ sung HSPL",
  TEN_LABEL: "Đã bổ sung HSPL",
  // ELEVEN_LABEL: "Đang khảo sát",
  TWELVE_LABEL: "Hoàn thành BBKS",
  // THIRTEEN_LABEL: "Lập tờ trình",
  FOURTEEN_LABEL: "Chờ duyệt",
  FIFTEEN_LABEL: "Đang duyệt",
  SIXTEEN_LABEL: "Đã duyệt",
  SEVENTEEN_LABEL: "Đã từ chối duyệt và chờ điều chỉnh",
  NINETEEN_LABEL: "Đã ký số",
  TWENTY_LABEL: "Đã gửi thông báo kết quả TĐ",
  TWENTY_ONE_LABEL: "Đã gửi kết quả TĐ",
  FORTY_ONE_LABEL: "Đã huỷ",

  //label for re-pricing: LOS, manual
  RE_PRICING_LOS_LABEL: "Hồ sơ tạo tự động",
  RE_PRICING_MANUAL_LABEL: "Tạo hồ sơ tự động",

  //label for refused appraisal
  REFUSED_NO_PRICE: "Từ chối không định giá",
  REFUSED_TO_NEW: "Từ chối để tạo yêu cầu mới",
};
export const ROLE_STATUS = {
  ZERO: 0,
  ONE: 1,
  ZERO_LABEL: "Ngừng hoạt động",
  ONE_LABEL: "Đang hoạt động",
};
export const APPROVAL_STATUS_LABEL: { [key: number]: string } = {
  [-1]: "Chưa gửi duyệt",
  0: "Chờ phê duyệt",
  1: "Đang duyệt",
  2: "Đã từ chối, Chờ điều chỉnh",
  3: "Đã phê duyệt",
};
export const APPROVAL_STATUS = {
  NOT_APPROVAL: -1,
  NOT_APPROVED: 0,
  APPROVING: 1,
  REJECTED: 2,
  APPROVED: 3,
};
export const APPRAISAL_IMAGE_UPLOAD_TYPE = {
  // TAB hình ảnh
  // Upload hình ảnh
  NORMAL_IMAGE: 2,
  // Ảnh sơ đồ
  DIAGRAM_IMAGE: 5,
  // Hình ảnh phụ lục tài sản
  APPENDIX_IMAGE: 1,

  // TAB định vị
  // bản đồ định vị
  LOCATION_IMAGE: 3,
  // Quy hoạch
  PLAN_IMAGE: 4,

  // bản đồ thể hiện tstd và tsss
  MAP_TSTD_AND_TSSS: 7,
  // ảnh định vị - động sản
  LOCATION_IMAGES: 8,
  UPLOAD_IMAGES_MAP_TSTD_AND_TSSS: 9,
  PROPERTY_VALUE_ASSET_IMAGE: 10,
};
export const ASSET_PRICES_SHARED_TYPE = {
  // nhà đất
  PLAN_USING: 0,
  // Chung cư
  APARTMENT: 1,
  // ptvt đường bộ
  ROAD_VEHICLE: 2,
  // ptvt đường thuỷ
  WATERWAY_VEHICLE: 3,
  // máy móc thiết bị
  DEVICE: 4,
  // Dự án
  PROJECT: 5,
  // Dự toán
  ESTIMATE: 6,
};
export const listKhiaCanh = [
  "Tài chính",
  "Khách hàng",
  "Quy định nội bộ",
  "Học hỏi-phát triển",
];
export const listTypeDoc = [
  "Hồ sơ ngoại thành",
  "Hồ sơ tỉnh",
  "Hồ sơ dự án (Tài sản giá trị dưới 500 tỷ)",
  "Hồ sơ dự án (Tài sản giá trị từ 500 tỷ đến 1000 tỷ)",
  "Hồ sơ dự án (Tài sản giá trị trên 1000 tỷ)",
  "Hồ sơ dự toán (Tài sản giá trị dưới 100 tỷ)",
  "Hồ sơ dự toán (Tài sản giá trị từ 100 tỷ trở lên)",
  "Hồ sơ cây trồng, dây chuyền MMTB, PTĐT (Tài sản giá trị dưới 50 tỷ)",
  "Hồ sơ cây trồng, dây chuyền MMTB, PTĐT (Tài sản giá trị trên 50 tỷ dưới 100 tỷ)",
  "Hồ sơ cây trồng, dây chuyền MMTB, PTĐT (Tài sản giá trị từ 100 tỷ trở lên)",
];

export const LIQUIDITY_ADVANTAGE_OPTIONS = [
  { value: "1", label: "Tốt" },
  { value: "2", label: "Trung bình" },
  { value: "3", label: "Kém" },
];

export const APPROVAL_TAB_OPTIONS = [
  { value: "1", label: "Thông tin tờ trình" },
  { value: "2", label: "Thông tin biên bản họp ban" },
];

//PTĐB
export const ROAD_ADVANTAGE_OPTIONS = [
  { value: 21, label: "Xe ô tô con" },
  { value: 22, label: "Xe ô tô khách" },
  { value: 23, label: "Xe ô tô tải" },
  { value: 24, label: "Xe ô tô đầu kéo" },
  { value: 25, label: "Xe ô tô rơ-mooc, sơ mi rơ-mooc" },
  { value: 26, label: "Xe chuyên dùng" },
  { value: 27, label: "Xe 02 bánh" },
];

export const ROAD_FUEL_ADVANTAGE_OPTIONS = [
  { value: 18, label: "Xăng" },
  { value: 19, label: "Dầu" },
  { value: 20, label: "Điện" },
  { value: 21, label: "Hybrid (Xăng-Điện)" },
  { value: 22, label: "Khí CNG" },
  { value: 23, label: "Khác" },
];

export const ROAD_GEARBOX_ADVANTAGE_OPTIONS = [
  { value: 8, label: "Hộp số sàn MT (Manual Transmission)" },
  { value: 9, label: "Hộp số tự động AT (Automatic Transmission)" },
  {
    value: 10,
    label: "Hộp số tự động vô cấp CVT (Continuous Variable Transmission)",
  },
  { value: 11, label: "Hộp số ly hợp kép DCT (Dual Clutch Transmission)" },
  {
    value: 12,
    label: "Hộp số bán tự động MAT (Manual-Automatic Transmission)",
  },
  { value: 13, label: "Hộp số sang số trực tiếp DSG (Direct Shift Gearbox)" },
  {
    value: 14,
    label: "Hộp số tùy chọn số sàn hoặc tự động TT (Tiptronic Transmission)",
  },
];

export const ROAD_WHEELFORMULAS_ADVANTAGE_OPTIONS = [
  { value: 7, label: "Xe có một cầu chủ động 4×2" },
  { value: 8, label: "Xe có hai cầu chủ động 4×4" },
  { value: 9, label: "Xe có hai cầu chủ động, một cầu bị động 6×4" },
  { value: 10, label: "Xe có ba cầu chủ động 6×6" },
  { value: 11, label: "Xe có bốn cầu chủ động 8×8" },
  { value: 12, label: "Khác" },
];

export const BUSINESS_ADVANTAGE_OPTIONS = [
  { value: 1, label: "Tốt" },
  { value: 2, label: "Trung bình" },
  { value: 3, label: "Kém" },
];

export const DISPUTE_INFORMATION_OPTIONS = [
  {
    value: "1",
    label: "Có",
  },
  { value: "0", label: "Không" },
];

export const DISPUTE_PROJECT_INFORMATION_OPTIONS = [
  {
    label: "Không xác định",
    value: "2",
  },
  {
    label: "Có",
    value: "1",
  },
  {
    label: "Không",
    value: "0",
  },
];

export const PROJECT_PLANNING_INFO = [
  {
    label: "Có",
    value: "có",
  },
  {
    label: "Không",
    value: "không",
  },
];

export const APPRAISAL_STATUS_OPTIONS = [
  {
    label: APPRAISAL_FILE_STATUS.REFUSED_NO_PRICE,
    value: APPRAISAL_FILE_STATUS.REFUSED_NO_PRICE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.REFUSED_TO_NEW,
    value: APPRAISAL_FILE_STATUS.REFUSED_TO_NEW.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.ONE_LABEL,
    value: APPRAISAL_FILE_STATUS.ONE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.ONE_PLUS_LABEL,
    value: APPRAISAL_FILE_STATUS.LOS_RECEIVED.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.ZERO_LABEL,
    value: APPRAISAL_FILE_STATUS.ZERO.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.TWO_LABEL,
    value: APPRAISAL_FILE_STATUS.TWO.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.THREE_LABEL,
    value: APPRAISAL_FILE_STATUS.THREE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.SIX_LABEL,
    value: APPRAISAL_FILE_STATUS.SIX.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.SEVEN_LABEL,
    value: APPRAISAL_FILE_STATUS.SEVEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.EIGHT_LABEL,
    value: APPRAISAL_FILE_STATUS.EIGHT.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.NINE_LABEL,
    value: APPRAISAL_FILE_STATUS.NINE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.TEN_LABEL,
    value: APPRAISAL_FILE_STATUS.TEN.toString(),
  },
  // {
  //   label: APPRAISAL_FILE_STATUS.ELEVEN_LABEL,
  //   value: APPRAISAL_FILE_STATUS.ELEVEN.toString(),
  // },
  {
    label: APPRAISAL_FILE_STATUS.TWELVE_LABEL,
    value: APPRAISAL_FILE_STATUS.TWELVE.toString(),
  },
  // {
  //   label: APPRAISAL_FILE_STATUS.THIRTEEN_LABEL,
  //   value: APPRAISAL_FILE_STATUS.THIRTEEN.toString(),
  // },
  {
    label: APPRAISAL_FILE_STATUS.FOURTEEN_LABEL,
    value: APPRAISAL_FILE_STATUS.FOURTEEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.FIFTEEN_LABEL,
    value: APPRAISAL_FILE_STATUS.FIFTEEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.SIXTEEN_LABEL,
    value: APPRAISAL_FILE_STATUS.SIXTEEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.SEVENTEEN_LABEL,
    value: APPRAISAL_FILE_STATUS.SEVENTEEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.NINETEEN_LABEL,
    value: APPRAISAL_FILE_STATUS.NINETEEN.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.TWENTY_LABEL,
    value: APPRAISAL_FILE_STATUS.TWENTY.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.TWENTY_ONE_LABEL,
    value: APPRAISAL_FILE_STATUS.TWENTY_ONE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.FORTY_ONE_LABEL,
    value: APPRAISAL_FILE_STATUS.FORTY_ONE.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.MINUS_TWO_LABEL,
    value: APPRAISAL_FILE_STATUS.MINUS_TWO.toString(),
  },
];

export const APPRAISAL_REPRICING_STATUS_OPTIONS = [
  {
    label: APPRAISAL_FILE_STATUS.TWENTY_LABEL,
    value: APPRAISAL_FILE_STATUS.TWENTY.toString(),
  },
  {
    label: APPRAISAL_FILE_STATUS.TWENTY_ONE_LABEL,
    value: APPRAISAL_FILE_STATUS.TWENTY_ONE.toString(),
  },
];

export const axisShapeLandLocation: any = {
  "01": "105",
  "02": "105.5",
  "04": "105.75",
  "06": "106.5",
  "08": "106",
  "10": "104.75",
  "11": "103",
  "12": "103",
  "14": "104",
  "15": "104.75",
  "17": "106",
  "19": "106.5",
  "20": "107.25",
  "22": "107.75",
  "24": "107",
  "25": "104.75",
  "26": "105",
  "27": "105.5",
  "30": "105.5",
  "31": "105.75",
  "33": "105.5",
  "34": "105.5",
  "35": "105",
  "36": "105.5",
  "37": "105",
  "38": "105",
  "40": "104.75",
  "42": "105.5",
  "44": "106",
  "45": "106.25",
  "46": "107",
  "48": "107.75",
  "49": "107.75",
  "51": "108",
  "52": "108.25",
  "54": "108.5",
  "56": "108.25",
  "58": "108.25",
  "60": "108.5",
  "62": "107.5",
  "64": "108.5",
  "66": "108.5",
  "67": "108.5",
  "68": "107.75",
  "70": "106.25",
  "72": "105.5",
  "74": "105.75",
  "75": "107.75",
  "77": "107.75",
  "79": "105.75",
  "82": "105.75",
  "83": "105.75",
  "84": "105.5",
  "86": "105.5",
  "87": "105",
  "88": "105.75",
  "89": "104.75",
  "91": "104.5",
  "92": "105",
  "93": "105",
  "94": "105.5",
  "95": "105",
  "96": "104.5",
};

export const ROLES = {
  CVTD: "ROLE_CVTD",
  CBTH: "ROLE_CBTH",
  CBTM: "ROLE_PPTĐG",
  CVC: "ROLE_CVC",
  CVCC: "ROLE_CVCC",
  TPTĐG: "ROLE_TPTĐG",
  TGĐ: "ROLE_TGĐ",
  PTGĐ: "ROLE_PTGĐ",
  GĐCN: "ROLE_GĐCN",
  TPCNHN: "ROLE_TPCNHN",
  PGĐCN: "ROLE_PGĐCN",
  CT: "ROLE_CT",
  TBP: "ROLE_TBP",
  ADMIN: "ROLE_ADMIN",
};
export const FILE_SIZE_CONFIG = {
  FILE: 30, // mb
  IMAGE: 10, //mb
};
export const VIETNAM_ID = 232;

export const BUTTON_CODES = {
  cths_luu: "cths_luu",
  cths_tu_choi: "cths_tu_choi",
  cths_ycbshs: "cths_ycbshs",
  cths_phan_giao: "cths_phan_giao",
  cths_bao_phi: "cths_bao_phi",
  cths_pyc: "cths_pyc",
  cths_xuat_BBKS: "cths_xuat_BBKS",
  cths_xuat_TT: "cths_xuat_TT",
  cths_xuat_TB_KQ: "cths_xuat_TB_KQ",
  cths_gui_duyet: "cths_gui_duyet",
  cths_phe_duyet: "cths_phe_duyet",
  cths_thay_the: "cths_thay_the",
  cths_tiep_nhan: "cths_tiep_nhan",
  pl_luu: "pl_luu",
  tt_gui_duyet: "tt_gui_duyet",
  tt_phe_duyet: "tt_phe_duyet",
  tt_tu_choi: "tt_tu_choi",
  ks_dieu_chi_nks: "ks_dieu_chi_nks",
  ks_ky_so: "ks_ky_so",
  ks_tu_choi: "ks_tu_choi",
  hsd_phan_giao: "hsd_phan_giao",
  hst_them_moi_hs: "hst_them_moi_hs",
  dgn_bds_them: "dgn_bds_them",
  dgn_chcc_them: "dgn_chcc_them",
  tdg_tai_dinh_gia: "tdg_tai_dinh_gia",
  bds_gui_duyet: "bds_gui_duyet",
  chcc_gui_duyet: "chcc_gui_duyet",
  ptdb_gui_duyet: "ptdb_gui_duyet",
  ptdt_gui_duyet: "ptdt_gui_duyet",
  mmtb_gui_duyet: "mmtb_gui_duyet",
  dutoan_gui_duyet: "dutoan_gui_duyet",
  duan_gui_duyet: "duan_gui_duyet",
  dscd_duyet_all: "dscd_duyet_all",
  kgbds_xuat_du_lieu: "kgbds_xuat_du_lieu",
  kgchcc_xuat_du_lieu: "kgchcc_xuat_du_lieu",
  kgptdb_xuat_du_lieu: "kgptdb_xuat_du_lieu",
  kgmmtb_xuat_du_lieu: "kgmmtb_xuat_du_lieu",
  kgptdt_xuat_du_lieu: "kgptdt_xuat_du_lieu",
  kgda_xuat_du_lieu: "kgda_xuat_du_lieu",
  kgdt_xuat_du_lieu: "kgdt_xuat_du_lieu",
  kgdctt_them: "kgdctt_them",
  kgdctt_sua: "kgdctt_sua",
  kgdctt_xoa: "kgdctt_xoa",
  tddt_cn_dong_bo_tu_ems: "tddt_cn_dong_bo_tu_ems",
  hscxd_dong_bo_ems: "hscxd_dong_bo_ems",
  hscxs_gui_ems: "hscxs_gui_ems",
  hscxd_doi_chieu: "hscxd_doi_chieu",
  hscxd_sua: "hscxd_sua",
  sptc_dong_bo_ems: "sptc_dong_bo_ems",
  bchsht_export: "bchsht_export",
  bchspst_export: "bchspst_export",
  bcth_export: "bcth_export",
  bccn_export: "bccn_export",
  bcttd_export: "bcttd_export",
  bckpi_export: "bckpi_export",
  bc_cong_no_export: "bc_cong_no_export",
  dm_gtvcn_luu: "dm_gtvcn_luu",
  dm_bieu_phi_them: "dm_bieu_phi_them",
  dm_bieu_phi_sua: "dm_bieu_phi_sua",
  dm_bieu_phi_xoa: "dm_bieu_phi_xoa",
  dm_ctp_them: "dm_ctp_them",
  dm_ctp_sua: "dm_ctp_sua",
  dm_ctp_xoa: "dm_ctp_xoa",
  dm_kpi_them: "dm_kpi_them",
  dm_kpi_sua: "dm_kpi_sua",
  dm_kpi_xoa: "dm_kpi_xoa",
  dm_cbrr_them: "dm_cbrr_them",
  dm_cbrr_sua: "dm_cbrr_sua",
  dm_cbrr_xoa: "dm_cbrr_xoa",
  dm_nntn_them: "dm_nntn_them",
  dm_nntn_sua: "dm_nntn_sua",
  dm_nntn_xoa: "dm_nntn_xoa",
  dm_chd_them: "dm_chd_them",
  dm_chd_edit: "dm_chd_edit",
  dm_chd_xoa: "dm_chd_xoa",
  dm_kgxvdt_them: "dm_kgxvdt_them",
  dm_kgxvdt_sua: "dm_kgxvdt_sua",
  dm_kgxvdt_xoa: "dm_kgxvdt_xoa",
  dm_hspl_them: "dm_hspl_them",
  dm_hspl_sua: "dm_hspl_sua",
  dm_hspl_xoa: "dm_hspl_xoa",
  dm_chi_nhanh_them: "dm_chi_nhanh_them",
  dm_chi_nhanh_sua: "dm_chi_nhanh_sua",
  dm_chi_nhanh_xoa: "dm_chi_nhanh_xoa",
  dm_kv_them: "dm_kv_them",
  dm_snck_them: "dm_snck_them",
  dm_snck_sua: "dm_snck_sua",
  dm_snck_xoa: "dm_snck_xoa",
  dm_nh_them: "dm_nh_them",
  dm_nh_sua: "dm_nh_sua",
  dm_nh_xoa: "dm_nh_xoa",
  nqtk_them: "nqtk_them",
  nqtk_sua: "nqtk_sua",
  nqtk_xoa: "nqtk_xoa",
  dstk_them: "dstk_them",
  dstk_sua: "dstk_sua",
  dstk_xoa: "dstk_xoa",
  pqtk_luu: "pqtk_luu",
  ppcn_luu: "ppcn_luu",
  mtdtkt_them: "mtdtkt_them",
  mtdtkt_sua: "mtdtkt_sua",
  mtdtkt_xoa: "mtdtkt_xoa",

  ct_tsss_phe_duyet: "ct_tsss_phe_duyet",
  ct_tsss_tu_choi: "ct_tsss_tu_choi",
  ctdtcn_dong_bo_tu_ems: "ctdtcn_dong_bo_tu_ems",
  ctdtcn_upload_tb_da_xn: "ctdtcn_upload_tb_da_xn",
  ctdtcn_yeu_cau_thu_tien: "ctdtcn_yeu_cau_thu_tien",
  ctdtcn_de_nghi_xuat_hd: "ctdtcn_de_nghi_xuat_hd",
  ctdtcn_thu_hoi_xuat_hd: "ctdtcn_thu_hoi_xuat_hd",
  ctdtcn_tra_xac_nhan: "ctdtcn_tra_xac_nhan",
  ctdtcn_xac_nhan: "ctdtcn_xac_nhan",
  ctdtcn_luu: "Lưu",
  ctdtcn_xem_tb_da_xn: "ctdtcn_xem_tb_da_xn",

  hst_xem_danh_sach: "hst_xem_danh_sach",
  cths_xem_chi_tiet: "cths_xem_chi_tiet",
  pl_xem_chi_tiet: "pl_xem_chi_tiet",
  tt_xem_chi_tiet: "tt_xem_chi_tiet",
  ks_xem_chi_tiet: "ks_xem_chi_tiet",
  dgn_bds_xem: "dgn_bds_xem",
  dgn_chcc_xem: "dgn_chcc_xem",
  tdg_xem_chi_tiet: "tdg_xem_chi_tiet",
  dscd_xem_chi_tiet: "dscd_xem_chi_tiet",
  kgc_xem_danh_sach: "kgc_xem_danh_sach",
  kgct_xem_danh_sach: "Xem danh sách, chi tiết TSSS",
  // kgct_bds_xem_danh_sach: "kgct_bds_xem_danh_sach",
  // kgct_bds_xem_chi_tiet: "kgct_bds_xem_chi_tiet",
  // kgct_chcc_xem_danh_sach: "kgct_chcc_xem_danh_sach",
  // kgct_chcc_xem_chi_tiet: "kgct_chcc_xem_chi_tiet",
  // kgct_ptdb_xem_danh_sach: "kgct_ptdb_xem_danh_sach",
  // kgct_ptdb_xem_chi_tiet: "kgct_ptdb_xem_chi_tiet",
  // kgct_ptdt_xem_danh_sach: "kgct_ptdt_xem_danh_sach",
  // kgct_ptdt_xem_chi_tiet: "kgct_ptdt_xem_chi_tiet",
  // kgct_mmtb_xem_danh_sach: "kgct_mmtb_xem_danh_sach",
  // kgct_mmtb_xem_chi_tiet: "kgct_mmtb_xem_chi_tiet",
  // kgct_da_xem_danh_sach: "kgct_da_xem_danh_sach",
  // kgct_da_xem_chi_tiet: "kgct_da_xem_chi_tiet",
  // kgct_dt_xem_danh_sach: "kgct_dt_xem_danh_sach",
  // kgct_dt_xem_chi_tiet: "kgct_dt_xem_chi_tiet",
  kgdctt_xem_danh_sach: "kgdctt_xem_danh_sach",
  tddt_cn_xem_danh_sach: "tddt_cn_xem_danh_sach",
  tddt_cn_xem_chi_tiet: "tddt_cn_xem_chi_tiet",
  hscxd_xem_danh_sach: "hscxd_xem_danh_sach",

  bchsht_xem_danh_sach: "bchsht_xem_danh_sach",
  bchspst_xem_danh_sach: "bchspst_xem_danh_sach",
  bcttd_xem_danh_sach: "bcttd_xem_danh_sach",
  bcth_xem_danh_sach: "bcth_xem_danh_sach",
  bc_cong_no_xem_danh_sach: "bc_cong_no_xem_danh_sach",
  bckpi_xem_danh_sach: "bckpi_xem_danh_sach",
  bccn_xem_danh_sach: "bccn_xem_danh_sach",

  nqtk_xem_danh_sach: "nqtk_xem_danh_sach",
  dstk_xem_danh_sach: "dstk_xem_danh_sach",
  pqtk_xem_danh_sach: "pqtk_xem_danh_sach",
  pqcn_xem_danh_sach: "pqcn_xem_danh_sach",
  dm_chi_nhanh_xem_danh_sach: "dm_chi_nhanh_xem_danh_sach",
  dm_snck_xem_danh_sach: "dm_snck_xem_danh_sach",
  dm_gtvcn_xem_danh_sach: "dm_gtvcn_xem_danh_sach",
  dm_kv_xem_danh_sach: "dm_kv_xem_danh_sach",
  dm_bieu_phi_xem_danh_sach: "dm_bieu_phi_xem_danh_sach",
  dm_ctp_xem_danh_sach: "dm_ctp_xem_danh_sach",
  dm_kpi_xem_danh_sach: "dm_kpi_xem_danh_sach",
  dm_cbrr_xem_danh_sach: "dm_cbrr_xem_danh_sach",
  dm_nntr_xem_danh_sach: "dm_nntr_xem_danh_sach",
  dm_chd_xem_danh_sach: "dm_chd_xem_danh_sach",
  dm_nh_xem_danh_sach: "dm_nh_xem_danh_sach",
  dm_ccplts_xem_danh_sach: "dm_ccplts_xem_danh_sach",
  dm_kgxvdt_xem_danh_sach: "dm_kgxvdt_xem_danh_sach",
  dm_hspl_xem_danh_sach: "dm_hspl_xem_danh_sach",
  dm_mdsd_xem_danh_sach: "dm_mdsd_xem_danh_sach",
  dm_mdsd_them: "dm_mdsd_them",
  dm_mdsd_sua: "dm_mdsd_sua",
  dm_mdsd_xoa: "dm_mdsd_xoa",
  dm_plts_xem: "dm_plts_xem",
  dm_plts_them: "dm_plts_them",
  dm_plts_sua: "dm_plts_sua",

  mtdtkt_xem_danh_sach: "mtdtkt_xem_danh_sach",
  ctdtcn_tbkq_xem: "ctdtcn_tbkq_xem",
  ctdtcn_tbkq_sua: "ctdtcn_tbkq_sua",
  hs_du_dieu_kien_xuat_hoa_don_xem: "hs_du_dieu_kien_xuat_hoa_don_xem",
  hs_du_dieu_kien_xuat_hoa_don_export: "hs_du_dieu_kien_xuat_hoa_don_export",
  hst_xem_theo_don_vi_dinh_gia: "hst_xem_theo_don_vi_dinh_gia",
  hst_xem_tat_ca_ho_so: "hst_xem_tat_ca_ho_so",
  kgdctt_xem: "kgdctt_xem",
  dm_ctxd_xem: "dm_ctxd_xem",
  dm_ctxd_them: "dm_ctxd_them",
  dm_ctxd_sua: "dm_ctxd_sua",

  dm_nhl_xem: "dm_nhl_xem",
  dm_nhl_them: "dm_nhl_them",
  dm_nhl_sua: "dm_nhl_sua",
  dm_nhl_xoa: "dm_nhl_xoa",
  dm_sla_xem: "dm_sla_xem",
  cths_upload_ngoai: "cths_upload_ngoai",

  // Danh mục phòng ban, vị trí
  dm_phong_ban_xem: "dm_phong_ban_xem",
  dm_phong_ban_them: "dm_phong_ban_them",
  dm_phong_ban_sua: "dm_phong_ban_sua",
  dm_phong_ban_xoa: "dm_phong_ban_xoa",
  dm_vi_tri_xem: "dm_vi_tri_xem",
  dm_vi_tri_them: "dm_vi_tri_them",
  dm_vi_tri_sua: "dm_vi_tri_sua",
  dm_vi_tri_xoa: "dm_vi_tri_xoa",
};
export const BUTTON_NAMES: Record<string, string> = {
  cths_luu: "Lưu thông tin hồ sơ",
  cths_tu_choi: "Từ chối định giá",
  cths_ycbshs: "Y/C bổ sung hồ sơ",
  cths_phan_giao: "Phân giao",
  cths_bao_phi: "Báo phí",
  cths_pyc: "Xuất phiếu YC",
  cths_xuat_BBKS: "Xuất BBKS",
  cths_xuat_TT: "Xuất tờ trình",
  cths_xuat_TB_KQ: "Xuất TB + KQTĐG",
  cths_gui_duyet: "Gửi duyệt",
  cths_phe_duyet: "Phê duyệt",
  cths_thay_the: "HS được thay thế",
  cths_tiep_nhan: "Tiếp nhận",
  pl_luu: "Lưu",
  tt_gui_duyet: "Gửi duyệt",
  tt_phe_duyet: "Phê Duyệt",
  tt_tu_choi: "Từ chối",
  ks_dieu_chi_nks: "Điều chỉnh người ký sô",
  ks_ky_so: "Ký số",
  ks_tu_choi: "Từ chối",
  hsd_phan_giao: "Phân giao",
  hst_them_moi_hs: "Thêm mới Hồ sơ",
  dgn_bds_them: "Thêm",
  dgn_chcc_them: "Thêm",
  tdg_tai_dinh_gia: "Tái định giá",
  bds_gui_duyet: "Gửi duyệt",
  chcc_gui_duyet: "Gửi duyệt",
  ptdb_gui_duyet: "Gửi duyệt",
  ptdt_gui_duyet: "Gửi duyệt",
  mmtb_gui_duyet: "Gửi duyệt",
  dutoan_gui_duyet: "Gửi duyệt",
  duan_gui_duyet: "Gửi duyệt",
  dscd_duyet_all: "Duyệt tất cả",
  kgbds_xuat_du_lieu: "Xuất dữ liệu",
  kgchcc_xuat_du_lieu: "Xuất dữ liệu",
  kgptdb_xuat_du_lieu: "Xuất dữ liệu",
  kgmmtb_xuat_du_lieu: "Xuất dữ liệu",
  kgptdt_xuat_du_lieu: "Xuất dữ liệu",
  kgda_xuat_du_lieu: "Xuất dữ liệu",
  kgdt_xuat_du_lieu: "Xuất dữ liệu",
  kgdctt_them: "Thêm",
  kgdctt_sua: "Sửa",
  kgdctt_xoa: "Xóa",
  tddt_cn_dong_bo_tu_ems: "Đồng bộ",
  hscxd_dong_bo_ems: "Đồng bộ",
  hscxs_gui_ems: "Gửi",
  hscxd_doi_chieu: "Đối chiếu",
  hscxd_sua: "Sửa trạng thái",
  sptc_dong_bo_ems: "Đồng bộ",
  bchsht_export: "Xuất dữ liệu",
  bchspst_export: "Xuất dữ liệu",
  bcth_export: "Xuất dữ liệu",
  bccn_export: "Xuất dữ liệu",
  bcttd_export: "Xuất dữ liệu",
  bckpi_export: "Xuất dữ liệu",
  bc_cong_no_export: "Xuất dữ liệu",
  dm_gtvcn_luu: "Lưu",
  dm_bieu_phi_them: "Thêm",
  dm_bieu_phi_sua: "Sửa",
  dm_bieu_phi_xoa: "Xóa",
  dm_ctp_them: "Thêm",
  dm_ctp_sua: "Sửa",
  dm_ctp_xoa: "Xóa",
  dm_kpi_them: "Thêm",
  dm_kpi_sua: "Sửa",
  dm_kpi_xoa: "Xóa",
  dm_cbrr_them: "Thêm",
  dm_cbrr_sua: "Sửa",
  dm_cbrr_xoa: "Xóa",
  dm_nntn_them: "Thêm",
  dm_nntn_sua: "Sửa",
  dm_nntn_xoa: "Xóa",
  dm_chd_them: "Thêm",
  dm_chd_edit: "Sửa",
  dm_chd_xoa: "Xóa",
  dm_kgxvdt_them: "Thêm",
  dm_kgxvdt_sua: "Sửa",
  dm_kgxvdt_xoa: "Xóa",
  dm_hspl_them: "Thêm",
  dm_hspl_sua: "Sửa",
  dm_hspl_xoa: "Xóa",
  dm_chi_nhanh_them: "Thêm",
  dm_chi_nhanh_sua: "Sửa",
  dm_chi_nhanh_xoa: "Xóa",
  dm_kv_them: "Thêm",
  dm_snck_them: "Thêm",
  dm_snck_sua: "Sửa",
  dm_snck_xoa: "Xóa",
  dm_nh_them: "Thêm",
  dm_nh_sua: "Sửa",
  dm_nh_xoa: "Xóa",
  nqtk_them: "Thêm",
  nqtk_sua: "Sửa",
  nqtk_xoa: "Xóa",
  dstk_them: "Thêm",
  dstk_sua: "Sửa",
  dstk_xoa: "Xóa",
  pqtk_luu: "Lưu",
  ppcn_luu: "Lưu",
  mtdtkt_them: "Thêm",
  mtdtkt_sua: "Sửa",
  mtdtkt_xoa: "Xóa",

  ct_tsss_phe_duyet: "Phê duyệt",
  ct_tsss_tu_choi: "Từ chối",
  ctdtcn_dong_bo_tu_ems: "Đồng bộ từ EMS",
  ctdtcn_upload_tb_da_xn: "Upload TB đã XN",
  ctdtcn_yeu_cau_thu_tien: "Yêu cầu thu tiền",
  ctdtcn_de_nghi_xuat_hd: "Đề nghị xuất HĐ",
  ctdtcn_thu_hoi_xuat_hd: "Thu hồi xuất hoá đơn",
  ctdtcn_tra_xac_nhan: "Trả xác nhận",
  ctdtcn_xac_nhan: "Xác nhận",
  ctdtcn_luu: "Lưu",
  ctdtcn_xem_tb_da_xn: "Xem TB đã XN",

  hst_xem_danh_sach: "Xem danh sách hồ sơ",
  cths_xem_chi_tiet: "Xem chi tiết hồ sơ",
  pl_xem_chi_tiet: "Xem chi tiết phụ lục",
  tt_xem_chi_tiet: "Xem chi tiết tờ trình",
  ks_xem_chi_tiet: "Xem chi tiết TB, KQ thẩm định",
  dgn_bds_xem: "Xem danh sách, chi tiết",
  dgn_chcc_xem: "Xem danh sách, chi tiết",
  tdg_xem_chi_tiet: "Xem danh sách TĐG",
  dscd_xem_chi_tiet: "Xem chi tiết TSSS",
  kgc_xem_danh_sach: "Xem danh sách, chi tiết TSSS",
  kgct_xem_danh_sach: "Xem danh sách, chi tiết TSSS",
  // kgct_bds_xem_danh_sach: "Xem danh sách kho giá BĐS",
  // kgct_bds_xem_chi_tiet: "Xem chi tiết kho giá BĐS",
  // kgct_chcc_xem_danh_sach: "Xem danh sách kho giá CHCC",
  // kgct_chcc_xem_chi_tiet: "Xem chi tiết kho giá CHCC",
  // kgct_ptdb_xem_danh_sach: "Xem danh sách kho giá PTĐB",
  // kgct_ptdb_xem_chi_tiet: "Xem chi tiết kho giá PTĐB",
  // kgct_ptdt_xem_danh_sach: "Xem danh sách kho giá PTĐT",
  // kgct_ptdt_xem_chi_tiet: "Xem chi tiết kho giá PTĐT",
  // kgct_mmtb_xem_danh_sach: "Xem danh sách kho giá MMTB",
  // kgct_mmtb_xem_chi_tiet: "Xem chi tiết kho giá MMTB",
  // kgct_da_xem_danh_sach: "Xem danh sách kho giá dự án",
  // kgct_da_xem_chi_tiet: "Xem chi tiết kho giá dự án",
  // kgct_dt_xem_danh_sach: "Xem danh sách kho giá dự toán",
  // kgct_dt_xem_chi_tiet: "Xem chi tiết kho giá dự toán",
  kgdctt_xem_danh_sach: "Xem danh sách",
  tddt_cn_xem_danh_sach: "Xem danh sách",
  tddt_cn_xem_chi_tiet: "Xem chi tiết doanh thu - công nợ",
  hscxd_xem_danh_sach: "Xem danh sách",

  bchsht_xem_danh_sach: "Xem danh sách",
  bchspst_xem_danh_sach: "Xem danh sách",
  bcttd_xem_danh_sach: "Xem danh sách",
  bcth_xem_danh_sach: "Xem danh sách",
  bc_cong_no_xem_danh_sach: "Xem danh sách",
  bckpi_xem_danh_sach: "Xem danh sách",
  bccn_xem_danh_sach: "Xem danh sách",

  nqtk_xem_danh_sach: "Xem danh sách",
  dstk_xem_danh_sach: "Xem danh sách",
  pqtk_xem_danh_sach: "Xem danh sách",
  pqcn_xem_danh_sach: "Xem danh sách",
  dm_chi_nhanh_xem_danh_sach: "Xem danh sách",
  dm_snck_xem_danh_sach: "Xem danh sách",
  dm_gtvcn_xem_danh_sach: "Xem danh sách",
  dm_kv_xem_danh_sach: "Xem danh sách",
  dm_bieu_phi_xem_danh_sach: "Xem danh sách",
  dm_ctp_xem_danh_sach: "Xem danh sách",
  dm_kpi_xem_danh_sach: "Xem danh sách",
  dm_cbrr_xem_danh_sach: "Xem danh sách",
  dm_nntr_xem_danh_sach: "Xem danh sách",
  dm_chd_xem_danh_sach: "Xem danh sách",
  dm_nh_xem_danh_sach: "Xem danh sách",
  dm_ccplts_xem_danh_sach: "Xem danh sách",
  dm_kgxvdt_xem_danh_sach: "Xem danh sách",
  dm_hspl_xem_danh_sach: "Xem danh sách",
  dm_mdsd_xem_danh_sach: "Xem danh sách",
  dm_mdsd_them: "Thêm",
  dm_mdsd_sua: "Sửa",
  dm_mdsd_xoa: "Xoá",
  dm_plts_xem: "Xem danh sách",
  dm_plts_them: "Thêm",
  dm_plts_sua: "Sửa",

  mtdtkt_xem_danh_sach: "Xem danh sách",

  ctdtcn_tbkq_xem: "Xem TBKQ",
  ctdtcn_tbkq_sua: "Cập nhật TBKQ",
  hs_du_dieu_kien_xuat_hoa_don_xem: "Xem",
  hs_du_dieu_kien_xuat_hoa_don_export: "Xuất dữ liệu",
  hst_xem_theo_don_vi_dinh_gia: "Xem theo đơn vị định giá",
  hst_xem_tat_ca_ho_so: "Xem tất cả hồ sơ",
  kgdctt_xem: "Xem danh sách",
  dm_ctxd_xem: "Xem DS CTXD",
  dm_ctxd_them: "Thêm CTXD",
  dm_ctxd_sua: "Sửa CTXD",

  dm_nhl_xem: "Xem danh sách",
  dm_nhl_them: "Thêm",
  dm_nhl_sua: "Sửa",
  dm_nhl_xoa: "Xoá",
  dm_sla_xem: "Xem",
  cths_upload_ngoai: "Upload ngoài",

  // Danh mục phòng ban, vị trí
  dm_phong_ban_xem: "Xem danh sách",
  dm_phong_ban_them: "Thêm",
  dm_phong_ban_sua: "Sửa",
  dm_phong_ban_xoa: "Xoá",
  dm_vi_tri_xem: "Xem danh sách",
  dm_vi_tri_them: "Thêm",
  dm_vi_tri_sua: "Sửa",
  dm_vi_tri_xoa: "Xoá",
};
export const renderButtonName = (code: string) => {
  const name = BUTTON_NAMES[code];
  return name || "-";
};
export const REFUSED_STATUS = {
  REFUSED_TO_PRICE: 0,
  REFUSED_TO_CREATE: 1,
  REFUSED_TO_PRICE_LABEL: "Từ chối không định giá",
  REFUSED_TO_CREATE_LABEL: "Từ chối để tạo phiếu yêu cầu mới",
};

export const REFUSED_RADIO_OPTIONS = [
  {
    label: REFUSED_STATUS.REFUSED_TO_PRICE_LABEL,
    value: REFUSED_STATUS.REFUSED_TO_PRICE,
  },
  {
    label: REFUSED_STATUS.REFUSED_TO_CREATE_LABEL,
    value: REFUSED_STATUS.REFUSED_TO_CREATE,
  },
];

export const KPI_BONUS_COEFFICIENT = {
  SURPASSING_KPI: "1",
  PERFORM_24H: "2",
  SURPASSING_KPI_LABEL: "Hệ số thưởng HS vượt KPI (đạt tiến độ) (VNĐ)",
  PERFORM_24H_LABEL: "Hệ số thưởng HS thưởng thực hiện 24h (VNĐ)",
};

export const KPI_BONUS_COEFFICIENT_OPTIONS = [
  {
    label: KPI_BONUS_COEFFICIENT.SURPASSING_KPI_LABEL,
    value: KPI_BONUS_COEFFICIENT.SURPASSING_KPI,
  },
  {
    label: KPI_BONUS_COEFFICIENT.PERFORM_24H_LABEL,
    value: KPI_BONUS_COEFFICIENT.PERFORM_24H,
  },
];

export const FEE_LIST_DOCUMENT = {
  TO_TRINH_GNNB: 10,
  TO_TRINH_GIAM_PHI: 11,
  TO_TRINH_DONG_Y_PHI: 12,
  FILE_THONG_BAO: 5,
  FILE_KET_QUA: 6,
  TO_TRINH_GNNB_LABEL: "Tờ trình GNNB",
  TO_TRINH_GIAM_PHI_LABEL: "Tờ trình giảm phí",
  TO_TRINH_DONG_Y_PHI_LABEL: "Tờ trình đồng ý phí",
  FILE_THONG_BAO_LABEL: "File thông báo",
  FILE_KET_QUA_LABEL: "File kết quả",
};

export const FEE_LIST_DOCUMENT_OPTIONS = [
  {
    label: FEE_LIST_DOCUMENT.TO_TRINH_GIAM_PHI_LABEL,
    value: FEE_LIST_DOCUMENT.TO_TRINH_GIAM_PHI,
  },
  {
    label: FEE_LIST_DOCUMENT.TO_TRINH_GNNB_LABEL,
    value: FEE_LIST_DOCUMENT.TO_TRINH_GNNB,
  },
];

export const SLA_TIMELINE_TYPE = {
  TIEP_NHAN: 0,
  PHAN_GIAO: 1,
  KHAO_SAT_LTT: 2,
  PHE_DUYET_1: 3,
  PHE_DUYET_2: 4,
  PHE_DUYET_3: 5,
  KY_SO: 6,
};

export const SLA_STATUS = {
  ON_TIME: "Đúng hạn",
  COMMITMENT_LATE: "Trễ cam kết",
  REGULATION_LATE: "Trễ quy định",
};
