import { ColumnsEdit } from "components/TableInputAddCustom/TableInputAddCustom";
import { TYPE_FIELD } from "constant/enums";
const { INPUT, SELECT } = TYPE_FIELD;
const dataSource = [
  {
    key: "1",
    name: "Thông tin tài sản",
    lable: "Mã kho",
    ts1: "-",
    typeFiled: false,
    required: false,
  },
  {
    key: "2",
    name: "Thông tin tài sản",
    lable: "Nguồn thông tin",
    ts1: 64,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "3",
    name: "Thông tin tài sản",
    lable: "Nguồn dữ liệu",
    ts1: 24,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "4",
    name: "Thông tin tài sản",
    lable: "Đơn vị định giá",
    ts1: 16,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "5",
    name: "Thông tin tài sản",
    lable: "Tình trạng giao dịch",
    ts1: 32,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "6",
    name: "Thông tin tài sản",
    lable: "Thời điểm",
    ts1: 62,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "7",
    name: "Thông tin tài sản",
    lable: "Người liên hệ - SĐT",
    ts1: 68,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "8",
    name: "Địa chỉ",
    lable: "Tỉnh/TP",
    ts1: 29,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "9",
    name: "Địa chỉ",
    lable: "Quận/Huyện/TP/Thị xã",
    ts1: 68,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "10",
    name: "Địa chỉ",
    lable: "Xã/Phường/Thị trấn",
    ts1: 16,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "11",
    name: "Địa chỉ",
    lable: "Đường phố",
    ts1: 24,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "12",
    name: "Địa chỉ",
    lable: "Vị trí",
    ts1: 24,
    typeFiled: SELECT,
    required: true,
  },
  {
    key: "13",
    name: "Địa chỉ",
    lable: "Số tờ",
    ts1: 24,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "14",
    name: "Địa chỉ",
    lable: "Số thửa",
    ts1: 24,
    typeFiled: INPUT,
  },
  {
    key: "15",
    name: "Địa chỉ",
    lable: "Chi tiết",
    ts1: 24,
    typeFiled: INPUT,
  },
  {
    key: "38",
    name: "Địa chỉ",
    lable: "Định vị",
    ts1: 24,
    typeFiled: "LOCAL",
  },
  {
    key: "37",
    name: "Chi tiết",
    lable: "Hình ảnh tài sản",
    ts1: 68,
    typeFiled: "IMAGE",
  },
  {
    key: "136",
    name: "Chi tiết",
    lable: "Tên dự án/Khu công nghiệp",
    ts1: 24,
    typeFiled: INPUT,
  },
  {
    key: "35",
    name: "Chi tiết",
    lable: "Diện tích khuôn viên (m²)",
    ts1: 24,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "16",
    name: "Chi tiết",
    lable: "Diện tích phù hợp quy hoạch (m²)",
    ts1: 48,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "17",
    name: "Chi tiết",
    lable: "Diện tích vi phạm lộ giới (m²)",
    ts1: 48,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "18",
    name: "Chi tiết",
    lable: "Diện tích(m²)",
    ts1: 68,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "19",
    name: "Chi tiết",
    lable: "Kích thước mặt tiền",
    ts1: 27,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "20",
    name: "Chi tiết",
    lable: "Số mặt tiền tiếp giáp",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "21",
    name: "Chi tiết",
    lable: "Hình dạng",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "22",
    name: "Chi tiết",
    lable: "Độ rộng ngõ/ngách nhỏ nhất (m)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "23",
    name: "Chi tiết",
    lable: "Khoảng cách tới trục đường chính (m)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "24",
    name: "Chi tiết",
    lable: "Lợi thế kinh doanh",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "34",
    name: "Chi tiết",
    lable: "Mục đích sử dụng đất",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "25",
    name: "Chi tiết",
    lable: "Yếu tố khác",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "26",
    name: "Chi tiết",
    lable: "Giá giao dịch/ rao bán (đồng)",
    ts1: 29,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "27",
    name: "Chi tiết",
    lable: "Giá rao bán (đồng)",
    ts1: 29,
    typeFiled: INPUT,
    required: true,
  },
  {
    key: "28",
    name: "Chi tiết",
    lable: "Tổng diện tích sàn XD (m²)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "29",
    name: "Chi tiết",
    lable: "Đơn giá XD (đồng/m²)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "30",
    name: "Chi tiết",
    lable: "CLCL (%)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "31",
    name: "Chi tiết",
    lable: "Giá trị CTXD (đồng)",
    ts1: 29,
    typeFiled: INPUT,
  },
  {
    key: "32",
    name: "Chi tiết",
    lable: "Loại đơn giá",
    ts1: 29,
    typeFiled: INPUT,
  },
];
const columnsTb: ColumnsEdit = [
  {
    title: "Nội dung",
    dataIndex: "name",
    key: "name",
    colSpan: 2,
  },
  {
    title: "lable",
    dataIndex: "lable",
    key: "lable",
    colSpan: 0,
  },
  {
    title: "TSSS",
    dataIndex: "ts1",
    key: "ts1",
  },
  //   {
  //     title: "TS 2",
  //     dataIndex: "ts2",
  //     key: "ts2",
  //   },
  //   {
  //     title: "TS 3",
  //     dataIndex: "ts3",
  //     key: "ts3",
  //   },
];

const renderRequire = (label: string) => (
  <>
    {label}
    <span style={{ color: "#F25B60" }}> *</span>
  </>
);

export { dataSource, columnsTb, renderRequire };
