import { DATE_TIME_FORMAT } from "./dateFormat";
import { COMPLETE_BY_TIME_REPORT_FILE } from "./completeByTimeReport";
import { ARISING_REPORT_FILE } from "./fileArising";

enum TYPE_FIELD {
  INPUT = "INPUT",
  SELECT = "SELECT",
  DATE_PICKER = "DATE_PICKER",
  INPUT_NUMBER = "INPUT_NUMBER",
  INPUT_PASSWORD = "INPUT_PASSWORD",
  SELECT_SEARCH = "SELECT_SEARCH",
  TEXT_AREA = "TEXT_AREA",
  AUTO_COMPLETE = "AUTO_SEARCH",
  RANGE_PICKER = "RANGE_PICKER",
  MULTI_SELECT_SEARCH = "MULTI_SELECT_SEARCH",
  CHECKBOX = "CHECKBOX",
  RADIO = "RADIO",
  MULTI_ITEMS = "MULTI_ITEMS",
  LOCAL = "LOCAL",
  IMAGE = "IMAGE",
  GET_LOCATION_BTN = "GET_LOCATION_BTN",
}

export { TYPE_FIELD, DATE_TIME_FORMAT, COMPLETE_BY_TIME_REPORT_FILE, ARISING_REPORT_FILE };
