import { ColumnsEdit } from "components/TableInputAddCustom/TableInputAddCustom";
import { AppraisalFileAssetCommonCreateType } from "constant/types";
import { Input } from "antd";

const columnsTableMenu: ColumnsEdit = [
  {
    key: 1,
    title: "STT",
    dataIndex: "stt",
    align: "center",
    width: "3%",
    render: (text, record, rowIndex) => rowIndex + 1,
  },
  {
    key: 2,
    title: "Nội dung",
    dataIndex: "noiDung",
    align: "center",
    width: "9%",
    className: "width-size-max",
    editable: true,
    selected: false,
  },
  {
    key: 3,
    title: "Mã",
    dataIndex: "ma",
    align: "center",
    width: "10%",
    selected: false,
    className: "width-size-max-asset",
    editable: true,
  },
  {
    key: 4,
    title: "DVT",
    dataIndex: "DVT",
    align: "center",
    width: "9%",
    className: "width-size-max",
    editable: true,
    selected: false,
  },
  {
    key: 5,
    title: "Số lượng",
    dataIndex: "soLuong",
    align: "center",
    width: "9%",
    className: "width-size-max",
    editable: true,
  },
  {
    key: 6,
    title: "Đơn giá",
    dataIndex: "gia",
    align: "center",
    width: "9%",
    selected: false,
    showSearch: true,
    className: "width-size-max",
    editable: true,
  },
  {
    key: 7,
    title: "VAT",
    dataIndex: "giaTriVAT",
    align: "center",
    width: "9%",
    selected: false,
    showSearch: true,
    className: "width-size-max",
    editable: true,
  },
  {
    key: 8,
    title: "Giảm phí",
    dataIndex: "giamPhi",
    align: "center",
    width: "10%",
    selected: false,
    showSearch: true,
    className: "width-size-max",
    editable: true,
  },
  {
    key: 9,
    title: "Thành tiền",
    dataIndex: "thanhTien",
    align: "center",
    width: "10%",
    selected: false,
    showSearch: true,
    className: "width-size-max",
    editable: true,
  },
  {
    key: 10,
    title: "Ghi chú",
    dataIndex: "ghiChu",
    align: "center",
    width: "10%",
    selected: false,
    showSearch: true,
    className: "width-size-max",
    editable: true,
  },
  {
    key: "action",
    dataIndex: "",
    align: "center",
    width: "4%",
    fixed: "right",
  },
];

const newItem: AppraisalFileAssetCommonCreateType = {
  addressDistrict: null,
  addressProvince: null,
  addressWard: null,
  appraisalTypeId: null,
  assetLevelThreeId: null,
  legalNumber: "",
  legalStatusId: null,
  addressDetail: "",
  addressStreet: "",
  appraisalType: null,
  assetLevelThree: null,
  districts: null,
  legalStatus: null,
  provinces: null,
  wards: null,
  description: "",
  key: "",
};

export { columnsTableMenu, newItem };
