import { ColumnsEdit } from "components/TableInputAddCustom/TableInputAddCustom";
import { AppraisalFileAssetCommonCreateType } from "constant/types";

const columnsTableMenu: ColumnsEdit = [
  // {
  //   key: 1,
  //   dataIndex: "assetCode",
  //   title: "Mã tài sản KG",
  //   align: "center",
  //   className: "width-size-max",
  //   width: "9%",
  //   editable: true,
  // },
  // {
  //   key: 2,
  //   dataIndex: "climsCode",
  //   title: "Mã CLIMS",
  //   align: "center",
  //   className: "width-size-max",
  //   width: "9%",
  //   editable: true,
  // },
  {
    key: 6,
    dataIndex: "appraisalTypeId",
    title: "Định giá qua SBA",
    align: "center",
    className: "width-size-max",
    selected: true,
  },
  {
    key: 3,
    title: "Phân loại tài sản",
    selected: true,
    align: "center",
    dataIndex: "assetLevelThreeId",
    className: "width-size-max-asset",
  },
  {
    key: 7,
    title: "Tình trạng pháp lý",
    dataIndex: "legalStatusId",
    align: "center",
    className: "width-size-max",
    selected: true,
  },
  // {
  //   key: 8,
  //   title: "Số GCN/HĐ",
  //   dataIndex: "legalNumber",
  //   align: "center",
  //   className: "width-size-max",
  //   width: "9%",
  //   editable: true,
  // },
  {
    key: 9,
    title: "Tỉnh/Thành phố",
    dataIndex: "addressProvince",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 10,
    title: "Quận/Huyện/Thị xã/TP",
    dataIndex: "addressDistrict",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 11,
    title: "Xã/Phường/Thị trấn",
    dataIndex: "addressWard",
    align: "center",
    className: "width-size-max",
    selected: true,
    showSearch: true,
  },
  {
    key: 12,
    title: "Mô tả chi tiết",
    dataIndex: "description",
    align: "center",
    className: "width-size-max",
    selected: false,
    editable: true,
    maxLength: 255,
    placeholder: "Nhập",
    popupInput: true,
  },
  {
    key: "action",
    dataIndex: "",
    align: "center",
    width: "4%",
    fixed: "right",
  },
];

const newItem: AppraisalFileAssetCommonCreateType = {
  addressDistrict: null,
  addressProvince: null,
  addressWard: null,
  appraisalTypeId: null,
  assetLevelThreeId: null,
  legalNumber: "",
  legalStatusId: null,
  addressDetail: "",
  addressStreet: "",
  appraisalType: null,
  assetLevelThree: null,
  districts: null,
  legalStatus: null,
  provinces: null,
  wards: null,
  description: "",
  key: "",
  orderBy: 0,
};

export { columnsTableMenu, newItem };
