import { TYPE_FIELD } from "constant/enums";
import { ColProps } from "antd";
import { Rule } from "antd/es/form";

export type InputFiledParams = {
  key: number | string;
  error?: any;
  touched?: any;
  type?: TYPE_FIELD;
  dataIndex?: string;
  disable?: boolean;
  span?: number;
  showTime?: boolean;
  options?: { value: string | number | null; label: string }[];
  optionsAutocomplete?: { value: string | number }[];
  value?: any;
  max?: number;
  onKeyPress?: any;
  css?: ColProps;
  size?: "small" | "middle" | "large";
  labelCol?: ColProps;
  selectMultiple?: boolean;
  require?: boolean;
  wrapperCol?: ColProps;
  min?: number;
  formatDatetime?: string;
  addonAfter?: string;
  percentable?: boolean;
  currencable?: boolean;
  isRounded?: boolean;
  placeholder?: string;
  formatter?: (data?: string | number) => string;
  parser?: (data?: string) => string;
  label?: any;
  onChange?: any;
  onKeyUp?: any;
  onSelect?: (value: string) => void;
  onClick?: any;
  onSearch?: any;
  showCount?: boolean;
  suffixIcon?: React.ReactNode;
  showSearch?: boolean;
  allowClear?: boolean;
  expand?: boolean;
  name?: any;
  rules?: Rule[];
  defaultValue?: any;
  prefix?: any;
  valuePropName?: string;
  className?: any;
  disabledDate?: any;
  maxLength?: number;
  toolTip?: string;
  textAreaHeight?: number;
};
